[[redirects]]
from = "https://www.blog.nomanaziz.me"
to = "https://blog.nomanaziz.me"
status = 301
force = true

[[redirects]]
from = "http://www.blog.nomanaziz.me"
to = "https://blog.nomanaziz.me"
status = 301
force = true
