[[redirects]]
from = "https://www.blog.saintmalik.me"
to = "https://blog.saintmalik.me"
status = 301
force = true

[[redirects]]
from = "http://www.blog.saintmalik.me"
to = "https://blog.saintmalik.me"
status = 301
force = true
