
// module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  module.exports = {
    docs: [
      {
        type: "doc",
        id: "intro",
      },
      {
        type: "category",
        label: "Solutions to Bugs from Day to Day Activities",
        items: [
          "auto-renew-self-signed-openssl-certificates",
        ],
      },
      // {
      //   type: "category",
      //   label: "Learning GoLang",
      //   items: [
      //     "variables-in-golang",
      //     "arrays-in-golang",
      //   ],
      // },
      // {
      //   type: "category",
      //   label: "Could Help You",
      //   items: [
      //     "custom-mails",
      //   ],
      // },
      // {
      //   type: "category",
      //   label: "Infrastructure as Code using Terraform(IaC)",
      //   items: [
      //     "terraform-kickstart",
      //   ],
      // },
    ],
  };